"""
dnb.py

This module provides functions and a class for discrete naive Bayes (DNB).


Functions
---------
discrete_naive_bayes:
  Generate a discrete naive Bayes model from training data.

is_discrete_naive_bayes:
  Check whether a model is a discrete naive Bayes model.

predict_dnb:
  Make predictions using a discrete naive Bayes model.

generate_disc:
  Generate discretizers for numerical variables.

apply_disc:
  Discretize numerical variables using fitted discretizers.

get_accuracy_score:
  Calculate the accuracy score.

get_iv:
  Return information value (IV) for variables.

plot_iv:
  Display information value (IV) plots for variables.

plot_woe:
  Display Weight of Evidence (WoE) plots for variables.


Example
-------
dnb = discrete_naive_bayes(X_train, y_train)
is_dnb = is_discrete_naive_bayes(dnb)

pred = predict_dnb(dnb, X_test)

disc = generate_disc(X_train, y_train)
X_d = apply_disc(disc, X_train)

acc_train = get_accuracy_score(dnb, X_train, y_train)
acc_test = get_accuracy_score(dnb, X_test, y_test)

iv = get_iv(dnb)
plot_iv(iv)
plot_woe(dnb)


Class
-----
DiscreteNaiveBayes:
  Scikit-learn-compatible estimator for discrete naive Bayes.


DiscreteNaiveBayes methods
--------------------------
fit:
  Fit the model to the training data.

predict:
  Predict class labels for samples.

predict_proba:
  Estimate class probabilities for samples.

score:
  Return the mean accuracy on the given data and labels.

get_iv:
  Return information value (IV) for variables.

plot_iv:
  Display information value (IV) plots for variables.

plot_woe:
  Display Weight of Evidence (WoE) plots for variables.

get_model:
  Return a model dictionary compatible with the discrete naive Bayes
  functions.


Example
-------
obj = DiscreteNaiveBayes()
obj.fit(X_train, y_train)

y_pred = obj.predict(X_test)
p = obj.predict_proba(X_test)[:, 1]

acc_train = obj.score(X_train, y_train)
acc_test = obj.score(X_test, y_test)

iv = obj.get_iv()
obj.plot_iv()
obj.plot_woe()

dnb = obj.get_model()


Author: annyms7519
Created: 2024-07-05
Last Modified: 2026-08-15
Version: 0.9.0
License: MIT

"""
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

LAPLACE = 1          # Default Laplace smoothing constant.
MAX_BIC = 0          # BIC threshold for discretizing numerical variables.
LOGI_MAX_ITER = 50   # Maximum number of iterations for logistic calibration.

def discrete_naive_bayes(
    X,
    y,
    weight=None,
    discretizer='bic',
    cross_fitting=False,
    n_splits=5,
    shuffle=True,
    random_state=None,
):
    """
    Generate a discrete naive Bayes model from training data.

    Args:
      X:
        DataFrame containing numerical or categorical variables.
      y:
        One-dimensional array-like target variable with the same number
        of observations as X.
      weight:
        Optional one-dimensional array-like object containing non-negative
        sample weights. It must have the same number of observations as X.
        If None, all sample weights are set to 1.0.
      discretizer:
        Discretization method. Must be "bic" or "mdlp".
      cross_fitting:
        Whether to use cross-fitted Weight of Evidence (WoE) values for
        the training data. If True, each observation is transformed using
        WoE values estimated without using the fold containing that
        observation.
      n_splits:
        Number of folds used for cross-fitting. Must be at least 2.
        This argument is used only when cross_fitting is True.
      shuffle:
        Whether to shuffle the observations before constructing the
        cross-fitting folds. This argument is used only when cross_fitting
        is True.
      random_state:
        Random seed used when constructing shuffled cross-fitting folds.
        This argument is effective only when both cross_fitting and shuffle
        are True.

    Returns:
      Dict containing the following keys:
        disc:
          Dictionary of discretizers generated by generate_disc.
        train:
          Trained discrete naive Bayes model generated by
          discrete_naive_bayes_main.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a DataFrame.")

    if not isinstance(cross_fitting, bool):
        raise TypeError("cross_fitting must be a boolean.")

    if not isinstance(n_splits, int) or isinstance(n_splits, bool):
        raise TypeError("n_splits must be an integer.")

    if n_splits < 2:
        raise ValueError("n_splits must be at least 2.")

    if not isinstance(shuffle, bool):
        raise TypeError("shuffle must be a boolean.")

    if (
        random_state is not None
        and (
            not isinstance(random_state, int)
            or isinstance(random_state, bool)
        )
    ):
        raise TypeError("random_state must be an integer or None.")

    disc = generate_disc(
        X,
        y,
        weight=weight,
        discretizer=discretizer,
    )

    X_d = apply_disc(
        disc,
        X,
    )

    train = discrete_naive_bayes_main(
        X_d,
        y,
        weight=weight,
        cross_fitting=cross_fitting,
        n_splits=n_splits,
        shuffle=shuffle,
        random_state=random_state,
        )

    model = {
        'disc': disc,
        'train': train,
    }

    return model

def discrete_naive_bayes_main(
    X,
    y,
    weight=None,
    cross_fitting=False,
    n_splits=5,
    shuffle=True,
    random_state=None,
):
    """
    Main function for training a discrete naive Bayes model.

    Args:
      X:
        DataFrame containing categorical variables.
        Numerical variables must be discretized beforehand.
      y:
        Binary target variable. ndarray, Series, or list.
      weight:
        Optional one-dimensional ndarray of sample weights.
        If None, all sample weights are set to 1.0.
        Negative values are clipped to 0.0.
      cross_fitting:
        Whether to use cross-fitted WoE values for the training data.
        If True, each observation is transformed using WoE values
        estimated without that observation's fold.
      n_splits:
        Number of folds used for cross-fitting.
        This argument is used only when cross_fitting=True.
      shuffle:
        Whether to shuffle observations before constructing the folds.
        This argument is used only when cross_fitting=True.
      random_state:
        Random seed used for fold construction when shuffle=True.
        This argument is used only when cross_fitting=True.

    Returns:
      Dict with the following keys:
        y_bool:
          Boolean Series representing the positive class.
        count:
          Dict containing category counts estimated from the full training data.
        woe:
          Dict containing WoE values estimated from the full training data.
          These values are used when transforming validation, test, or new data.
        woe_table:
          DataFrame containing WoE-transformed training variables.
          If cross_fitting=False, the WoE values are estimated from the full training data.
          If cross_fitting=True, cross-fitted WoE values are returned.
        fold:
          Series containing the validation-fold number assigned to each observation,
          if cross_fitting=True.
        raw_score:
          Sum of WoE values for each observation, if logi=True.
        probability:
          Probability estimates calculated as 1 / (1 + exp(-(c0 + c1 * raw_score))),
          if logi=True.
        c0:
          Logistic calibration intercept, if logi=True.
        c1:
          Logistic calibration coefficient, if logi=True.
        iter:
          Number of logistic calibration iterations, if logi=True.
    """
    y_bool = make_y_bool(
        y,
        index=X.index,
    )

    weight_array = make_sample_weight(
        weight,
        len(X),
    )

    if cross_fitting:
        woe_result = _calculate_cross_fitted_woe_main(
            X,
            y_bool,
            weight_array,
            n_splits=n_splits,
            shuffle=shuffle,
            random_state=random_state,
            laplace=LAPLACE,
        )
    else:
        woe_result = _calculate_woe_main_fast(
            X,
            y_bool,
            weight_array,
            LAPLACE,
        )

    raw_score = (
        woe_result["woe_table"]
        .sum(axis=1)
        .to_numpy(dtype=float)
    )

    logistic_result = _logistic_regression(
        raw_score,
        y_bool,
        weight_array,
    )

    return {
        "y_bool": y_bool,
        **woe_result,
        **logistic_result,
    }

def is_discrete_naive_bayes(
    model,
):
    """
    Check whether a model is a discrete naive Bayes model.
    """
    return (
        isinstance(model, dict)
        and {'disc', 'train'} <= model.keys()
    )

def predict_dnb(
    model,
    X,
):
    """
    Make predictions using a discrete naive Bayes model.

    Args:
      model:
        Trained discrete naive Bayes model generated by
        discrete_naive_bayes().
      X:
        DataFrame containing numerical or categorical variables
        corresponding to the samples to be predicted.

    Returns:
      Dict containing the following keys:
        raw_score:
          Array containing the total Weight of Evidence scores.
        probability:
          Array containing calibrated probability estimates for the
          target class.
    """
    if not isinstance(model, dict):
        raise TypeError("model must be a dictionary.")

    if not is_discrete_naive_bayes(model):
        raise ValueError(
            "model must be a discrete naive Bayes model generated by "
            "discrete_naive_bayes()."
        )

    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    variables = [
        var for var in X.columns
        if var in model["disc"]
    ]
    X = X[variables]

    train = model["train"]

    # Apply the discretization fitted on the training data.
    X_d = apply_disc(
        model["disc"],
        X,
    )

    # Apply the WoE mappings fitted on the training data.
    woe_table = apply_woe(
        X_d,
        train["woe"],
    )

    raw_score = (
        woe_table
        .sum(axis=1)
        .to_numpy(dtype=float)
    )

    probability = _calc_probability(
        train["c0"],
        train["c1"],
        raw_score,
    )

    return {
        "raw_score": raw_score,
        "probability": probability,
    }

def make_y_bool(
    y,
    index=None,
):
    """
    Convert a binary target variable into a boolean Series.

    The second category in pd.Categorical(y).categories is treated
    as the positive class (True).

    Args:
      y:
        One-dimensional array-like binary target variable.
      index:
        Index assigned to the returned Series.
        If y is a Series and index is None, y.index is used.
        Otherwise, a default RangeIndex is used when index is None.

    Returns:
      Boolean Series representing the positive class.
    """
    if isinstance(y, pd.Series):
        y_name = y.name

        if index is None:
            index = y.index
    else:
        y_name = None

    y_values = np.asarray(y)

    if y_values.ndim != 1:
        raise ValueError("y must be one-dimensional.")

    if index is None:
        index = pd.RangeIndex(len(y_values))

    if len(y_values) != len(index):
        raise ValueError(
            "y and index must have the same length."
        )

    ycat = pd.Categorical(y_values)

    if len(ycat.categories) != 2:
        raise ValueError("y must be binary.")

    return pd.Series(
        ycat == ycat.categories[1],
        index=index,
        name=y_name,
        dtype=bool,
    )

def make_sample_weight(
    weight,
    n_samples,
):
    """
    Validate and normalize sample weights.

    Args:
      weight:
        None or one-dimensional array-like sample weights.
        If None, all sample weights are set to 1.0.
      n_samples:
        Number of samples.

    Returns:
      One-dimensional ndarray of non-negative sample weights.
    """
    if not isinstance(n_samples, int) or isinstance(n_samples, bool):
        raise TypeError("n_samples must be an integer.")

    if n_samples < 0:
        raise ValueError("n_samples must be non-negative.")

    if weight is None:
        return np.ones(n_samples, dtype=float)

    try:
        weight = np.asarray(weight, dtype=float)
    except (TypeError, ValueError) as exc:
        raise TypeError(
            "weight must be array-like and contain numeric values."
        ) from exc

    if weight.ndim != 1:
        raise ValueError("weight must be one-dimensional.")

    if len(weight) != n_samples:
        raise ValueError(
            "weight must have the same length as the data."
        )

    if not np.isfinite(weight).all():
        raise ValueError(
            "weight must contain only finite values."
        )

    if (weight < 0).any():
        raise ValueError(
            "weight must contain only non-negative values."
        )

    return weight.copy()

def generate_disc(
    X,
    y,
    weight=None,
    discretizer='bic',
):
    """
    Generate discretizers for numerical variables.

    This function is used by discrete_naive_bayes() and other functions.

    Args:
      X:
        DataFrame containing numerical or categorical variables.
      y:
        One-dimensional array-like target variable with the same number
        of observations as X.
      weight:
        None or one-dimensional array-like sample weights with the same
        number of observations as X. If None, all sample weights are
        treated as 1.0.
      discretizer:
        Discretization method. Must be "bic" or "mdlp".

    Returns:
      Dictionary of discretizers whose keys are variable names.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    y = np.asarray(y)

    if y.ndim != 1:
        raise ValueError("y must be one-dimensional.")

    if len(y) != len(X):
        raise ValueError("y must have the same length as X.")

    if discretizer == "bic":
        return _generate_disc_bic_fast(
            X,
            y,
            weight,
        )

    if discretizer == "mdlp":
        return _generate_disc_mdlp_fast(
            X,
            y,
            weight,
        )

    raise ValueError(
        "discretizer must be 'bic' or 'mdlp'."
    )

from numba import njit

@njit(cache=True)
def _bic_2x2(tab11, tab12, tab21, tab22):
    total = tab11 + tab12 + tab21 + tab22

    ent_ij = (
        tab11 * np.log(tab11)
        + tab12 * np.log(tab12)
        + tab21 * np.log(tab21)
        + tab22 * np.log(tab22)
    )

    row1 = tab11 + tab12
    row2 = tab21 + tab22
    col1 = tab11 + tab21
    col2 = tab12 + tab22

    ent_i = row1 * np.log(row1) + row2 * np.log(row2)
    ent_j = col1 * np.log(col1) + col2 * np.log(col2)
    ent_all = total * np.log(total)

    return -2.0 * (ent_ij - ent_i - ent_j + ent_all) + np.log(total)


@njit(cache=True)
def _find_best_split(
    x,
    y,
    w,
    start,
    end,
    laplace,
    max_bic,
):
    if end - start < 2:
        return -1

    total0 = 0.0
    total1 = 0.0

    for i in range(start, end):
        if y[i]:
            total1 += w[i]
        else:
            total0 += w[i]

    left0 = 0.0
    left1 = 0.0

    best_bic = np.inf
    best_split = -1

    for i in range(start, end - 1):
        if y[i]:
            left1 += w[i]
        else:
            left0 += w[i]

        if x[i] == x[i + 1]:
            continue

        bic = _bic_2x2(
            left0 + laplace,
            total0 - left0 + laplace,
            left1 + laplace,
            total1 - left1 + laplace,
        )

        if bic < best_bic:
            best_bic = bic
            best_split = i + 1

    if best_bic >= max_bic:
        return -1

    return best_split


@njit(cache=True)
def _get_cut_points_numba(
    x,
    y,
    w,
    laplace,
    max_bic,
):
    n = x.shape[0]

    if n < 2:
        return np.empty(0, dtype=np.float64)

    cut_points = np.empty(n - 1, dtype=np.float64)
    n_cuts = 0

    stack_start = np.empty(n, dtype=np.int64)
    stack_end = np.empty(n, dtype=np.int64)

    stack_size = 1
    stack_start[0] = 0
    stack_end[0] = n

    while stack_size > 0:
        stack_size -= 1

        start = stack_start[stack_size]
        end = stack_end[stack_size]

        split = _find_best_split(
            x,
            y,
            w,
            start,
            end,
            laplace,
            max_bic,
        )

        if split == -1:
            continue

        cut_points[n_cuts] = (
            x[split - 1]
            + (x[split] - x[split - 1]) / 2.0
        )
        n_cuts += 1

        # Load the right side first, then the left side
        # Since it is LIFO, the left side is processed first
        stack_start[stack_size] = split
        stack_end[stack_size] = end
        stack_size += 1

        stack_start[stack_size] = start
        stack_end[stack_size] = split
        stack_size += 1

    result = cut_points[:n_cuts]
    result.sort()

    return result


def _generate_disc_bic_fast(
    X,
    y,
    weight=None,
    *,
    laplace=LAPLACE,
    max_bic=MAX_BIC,
    decimals=8,
):
    """
    Generate BIC-based discretizers for numerical variables.

    Args:
      X:
        DataFrame of numerical or categorical variables.
      y:
        Binary target. Array, Series, or list with the same length as X.
      weight:
        One-dimensional ndarray of sample weights.
        If None, all weights are set to 1.0.
      laplace:
        Laplace smoothing constant.
      max_bic:
        BIC threshold used to accept a split.
      decimals:
        Number of decimal places used to round numerical values.

    Returns:
      Dict whose keys are variable names and whose values are:
        ndarray of bin boundaries for numerical variables
        None for categorical variables
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    y_binary = (
        make_y_bool(y, index=X.index)
        .to_numpy(dtype=np.bool_, copy=False)
    )

    weight_array = make_sample_weight(
        weight,
        n_samples=len(X),
    )

    disc = {}

    for col in X.columns:
        xc = X[col]

        if (
            isinstance(xc.dtype, pd.CategoricalDtype)
            or pd.api.types.is_object_dtype(xc.dtype)
            or pd.api.types.is_string_dtype(xc.dtype)
        ):
            disc[col] = None
            continue

        x = xc.to_numpy(dtype=np.float64, copy=False)

        mask = np.isfinite(x) & (weight_array > 0)

        xx = np.ascontiguousarray(
            np.round(x[mask], decimals),
            dtype=np.float64,
        )
        yy = np.ascontiguousarray(
            y_binary[mask],
            dtype=np.bool_,
        )
        ww = np.ascontiguousarray(
            weight_array[mask],
            dtype=np.float64,
        )

        if xx.size < 2:
            disc[col] = np.array(
                [-np.inf, np.inf],
                dtype=np.float64,
            )
            continue

        order = np.argsort(xx, kind="mergesort")

        xx = np.ascontiguousarray(xx[order])
        yy = np.ascontiguousarray(yy[order])
        ww = np.ascontiguousarray(ww[order])

        cut_points = _get_cut_points_numba(
            xx,
            yy,
            ww,
            float(laplace),
            float(max_bic),
        )

        disc[col] = np.concatenate([
            [-np.inf],
            cut_points,
            [np.inf],
        ])

    return disc

from numba import njit

@njit(cache=True, inline="always")
def _binary_entropy(weight0, weight1):
    """
    Calculate weighted binary entropy.
    """
    total = weight0 + weight1

    if total <= 0.0:
        return 0.0

    entropy = 0.0

    if weight0 > 0.0:
        p0 = weight0 / total
        entropy -= p0 * np.log2(p0)

    if weight1 > 0.0:
        p1 = weight1 / total
        entropy -= p1 * np.log2(p1)

    return entropy


@njit(cache=True)
def _find_best_mdlp_split(
    x,
    y,
    w,
    prefix0,
    prefix1,
    start,
    end,
):
    """
    Find the best MDLP split in x[start:end].

    Args:
      x:
        Sorted numerical values.
      y:
        Boolean target sorted consistently with x.
      w:
        Sample weights sorted consistently with x.
      prefix0:
        Prefix sums of weights for y=False.
      prefix1:
        Prefix sums of weights for y=True.
      start:
        Inclusive start position.
      end:
        Exclusive end position.

    Returns:
      Position immediately to the right of the best split.
      Returns -1 if no acceptable split exists.
    """
    n_sub = end - start

    if n_sub < 2:
        return -1

    total0 = prefix0[end] - prefix0[start]
    total1 = prefix1[end] - prefix1[start]

    total_weight = total0 + total1

    if total_weight <= 0.0:
        return -1

    parent_entropy = _binary_entropy(
        total0,
        total1,
    )

    left0 = 0.0
    left1 = 0.0

    best_ig = -np.inf
    best_split = -1

    # For a binary target, k is at most 2.
    k = 0

    if total0 > 0.0:
        k += 1

    if total1 > 0.0:
        k += 1

    for i in range(start, end - 1):
        if y[i]:
            left1 += w[i]
        else:
            left0 += w[i]

        # A cut is only possible between different x values.
        if x[i] == x[i + 1]:
            continue

        right0 = total0 - left0
        right1 = total1 - left1

        left_weight = left0 + left1
        right_weight = right0 + right1

        if left_weight <= 0.0 or right_weight <= 0.0:
            continue

        left_entropy = _binary_entropy(
            left0,
            left1,
        )

        right_entropy = _binary_entropy(
            right0,
            right1,
        )

        information_gain = (
            parent_entropy
            - (left_weight / total_weight) * left_entropy
            - (right_weight / total_weight) * right_entropy
        )

        k_left = 0

        if left0 > 0.0:
            k_left += 1

        if left1 > 0.0:
            k_left += 1

        k_right = 0

        if right0 > 0.0:
            k_right += 1

        if right1 > 0.0:
            k_right += 1

        delta = (
            np.log2(3.0 ** k - 2.0)
            - (
                k * parent_entropy
                - k_left * left_entropy
                - k_right * right_entropy
            )
        )

        # Preserve the original implementation:
        # threshold uses the unweighted number of observations.
        threshold = (
            np.log2(n_sub - 1.0)
            + delta
        ) / n_sub

        if (
            information_gain > threshold
            and information_gain > best_ig
        ):
            best_ig = information_gain
            best_split = i + 1

    return best_split


@njit(cache=True)
def _make_binary_weight_prefix(y, w):
    """
    Construct class-specific prefix sums of sample weights.
    """
    n = y.shape[0]

    prefix0 = np.zeros(
        n + 1,
        dtype=np.float64,
    )

    prefix1 = np.zeros(
        n + 1,
        dtype=np.float64,
    )

    for i in range(n):
        prefix0[i + 1] = prefix0[i]
        prefix1[i + 1] = prefix1[i]

        if y[i]:
            prefix1[i + 1] += w[i]
        else:
            prefix0[i + 1] += w[i]

    return prefix0, prefix1


@njit(cache=True)
def _get_cut_points_mdlp_fast(
    x,
    y,
    w,
):
    """
    Calculate MDLP cut points from sorted arrays.

    Args:
      x:
        Sorted float64 array.
      y:
        Boolean array sorted consistently with x.
      w:
        Float64 weight array sorted consistently with x.

    Returns:
      Sorted float64 ndarray of cut points.
    """
    n = x.shape[0]

    if n < 2:
        return np.empty(
            0,
            dtype=np.float64,
        )

    prefix0, prefix1 = _make_binary_weight_prefix(
        y,
        w,
    )

    # At most n - 1 cut points can exist.
    cut_points = np.empty(
        n - 1,
        dtype=np.float64,
    )

    n_cuts = 0

    # Explicit stack avoids Python recursion and array slicing.
    stack_start = np.empty(
        n,
        dtype=np.int64,
    )

    stack_end = np.empty(
        n,
        dtype=np.int64,
    )

    stack_size = 1
    stack_start[0] = 0
    stack_end[0] = n

    while stack_size > 0:
        stack_size -= 1

        start = stack_start[stack_size]
        end = stack_end[stack_size]

        split = _find_best_mdlp_split(
            x,
            y,
            w,
            prefix0,
            prefix1,
            start,
            end,
        )

        if split < 0:
            continue

        cut_points[n_cuts] = (
            x[split - 1]
            + (x[split] - x[split - 1]) / 2.0
        )

        n_cuts += 1

        # Push right first and left second.
        # Because the stack is LIFO, the left interval is processed first.
        stack_start[stack_size] = split
        stack_end[stack_size] = end
        stack_size += 1

        stack_start[stack_size] = start
        stack_end[stack_size] = split
        stack_size += 1

    result = cut_points[:n_cuts]
    result.sort()

    return result


def _generate_disc_mdlp_fast(
    X,
    y,
    weight=None,
    *,
    decimals=8,
):
    """
    Generate MDLP-based discretizers for numerical variables.

    Numerical values are rounded and sorted once per variable.
    The MDLP split search is performed by Numba-compiled functions.

    Args:
      X:
        DataFrame containing numerical or categorical variables.
      y:
        Binary target. Array, Series, or list with the same length as X.
      weight:
        One-dimensional sample-weight array.
        If None, all weights are set to 1.0.
      decimals:
        Number of decimal places used when rounding numerical
        values before split-point calculation.

    Returns:
      Dict whose keys are variable names and whose values are:
        ndarray of bin boundaries for numerical variables
        None for categorical variables
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    if not isinstance(y, (np.ndarray, pd.Series, list)):
        raise TypeError(
            "y must be an ndarray, Series, or list."
        )

    if len(y) != len(X):
        raise ValueError(
            "y must have the same length as X."
        )

    y_binary = (
        make_y_bool(
            y,
            index=X.index,
        )
        .to_numpy(
            dtype=np.bool_,
            copy=False,
        )
    )

    weight_array = make_sample_weight(
        weight,
        len(X),
    )

    weight_array = np.asarray(
        weight_array,
        dtype=np.float64,
    )

    disc = {}

    for column in X.columns:
        xc = X[column]

        if (
            isinstance(xc.dtype, pd.CategoricalDtype)
            or pd.api.types.is_object_dtype(xc.dtype)
            or pd.api.types.is_string_dtype(xc.dtype)
        ):
            disc[column] = None
            continue

        x = xc.to_numpy(
            dtype=np.float64,
            copy=False,
        )

        valid = (
            np.isfinite(x)
            & (weight_array > 0.0)
        )

        xx = np.ascontiguousarray(
            np.round(
                x[valid],
                decimals=decimals,
            ),
            dtype=np.float64,
        )

        yy = np.ascontiguousarray(
            y_binary[valid],
            dtype=np.bool_,
        )

        ww = np.ascontiguousarray(
            weight_array[valid],
            dtype=np.float64,
        )

        if xx.size < 2:
            disc[column] = np.array(
                [-np.inf, np.inf],
                dtype=np.float64,
            )
            continue

        # Stable sorting keeps observations with equal x values
        # in their original relative order.
        order = np.argsort(
            xx,
            kind="mergesort",
        )

        xx = np.ascontiguousarray(
            xx[order],
            dtype=np.float64,
        )

        yy = np.ascontiguousarray(
            yy[order],
            dtype=np.bool_,
        )

        ww = np.ascontiguousarray(
            ww[order],
            dtype=np.float64,
        )

        cut_points = _get_cut_points_mdlp_fast(
            xx,
            yy,
            ww,
        )

        disc[column] = np.concatenate([
            np.array(
                [-np.inf],
                dtype=np.float64,
            ),
            cut_points,
            np.array(
                [np.inf],
                dtype=np.float64,
            ),
        ])

    return disc

def apply_disc(
    disc,
    X,
):
    """
    Discretize numerical variables using fitted discretizers.

    Args:
      disc:
        Dictionary whose keys are variable names.
      X:
        DataFrame containing numerical or categorical variables.

    Returns:
      DataFrame containing only categorical variables.
    """
    if not isinstance(disc, dict):
        raise TypeError("disc must be a dictionary.")

    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    missing_vars = [
        col for col in X.columns
        if col not in disc
    ]

    if missing_vars:
        raise ValueError(
            f"Discretizers are missing for variables: {missing_vars}"
        )

    xd = {}

    for col in X.columns:
        xc = X[col]
        dsc = disc[col]

        if (
            isinstance(xc.dtype, pd.CategoricalDtype)
            or pd.api.types.is_object_dtype(xc.dtype)
            or pd.api.types.is_string_dtype(xc.dtype)
        ):
            xd[col] = pd.Categorical(xc)

        elif dsc is not None:
            xd[col] = pd.cut(
                xc,
                bins=dsc,
                include_lowest=True,
            )

        else:
            raise ValueError(
                f"No discretizer is available for numerical variable {col!r}."
            )

    return pd.DataFrame(
        xd,
        index=X.index,
    )

def calculate_woe(
    X,
    y,
    weight=None,
    laplace=LAPLACE,
):
    """
    Calculate category counts and Weight of Evidence (WoE).

    Args:
      X:
        DataFrame containing categorical variables.
        Numerical variables must be discretized beforehand.
      y:
        Binary target variable. ndarray, Series, or list.
      weight:
        Optional one-dimensional ndarray of non-negative sample weights.
        If None, all sample weights are set to 1.0.
      laplace:
        Laplace smoothing constant.

    Returns:
      Dict with the following keys:
        count:
          Dict containing unweighted category counts for each variable.
        woe:
          Dict containing WoE values for each category of each variable.
        woe_table:
          DataFrame in which each category value is replaced by its WoE.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a DataFrame.")

    y_bool = make_y_bool(
        y,
        index=X.index,
    )

    weight_array = make_sample_weight(
        weight,
        len(X),
    )

    woe_result = _calculate_woe_main_fast(
        X,
        y_bool,
        weight_array,
        laplace,
    )

    return {
        "y_bool": y_bool,
        **woe_result,
    }

from numba import njit

@njit(cache=True)
def _aggregate_woe_numba(
    codes,
    y_array,
    weight_array,
    n_categories,
    laplace,
):
    counts = np.zeros(
        n_categories,
        dtype=np.int64,
    )

    negative_sum = np.full(
        n_categories,
        laplace,
        dtype=np.float64,
    )

    positive_sum = np.full(
        n_categories,
        laplace,
        dtype=np.float64,
    )

    for i in range(codes.shape[0]):
        code = codes[i]

        if code < 0 or weight_array[i] <= 0.0:
            continue

        counts[code] += 1

        if y_array[i]:
            positive_sum[code] += weight_array[i]
        else:
            negative_sum[code] += weight_array[i]

    negative_total = negative_sum.sum()
    positive_total = positive_sum.sum()

    category_woe = np.empty(
        n_categories,
        dtype=np.float64,
    )

    for j in range(n_categories):
        category_woe[j] = np.log(
            (positive_sum[j] / positive_total)
            / (negative_sum[j] / negative_total)
        )

    return counts, category_woe


def _calculate_woe_main_fast(
    X,
    y_bool,
    weight_array,
    laplace,
):
    """
    Calculate WoE using pandas.factorize and a Numba-compiled aggregator.

    Missing values and observations with non-positive weights are excluded
    from WoE estimation. Missing values receive a neutral WoE of 0.0 in the
    transformed table.

    Args:
      X:
        DataFrame containing categorical variables.
      y_bool:
        Boolean Series aligned with X by row position.
      weight_array:
        One-dimensional float ndarray aligned with X.
      laplace:
        Non-negative Laplace smoothing constant.

    Returns:
      Dict containing count, woe, and woe_table.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    if not isinstance(y_bool, pd.Series):
        raise TypeError("y_bool must be a pandas Series.")

    if y_bool.dtype != bool:
        raise TypeError("y_bool must be a boolean Series.")

    if not isinstance(weight_array, np.ndarray):
        raise TypeError("weight_array must be a NumPy ndarray.")

    if weight_array.ndim != 1:
        raise ValueError("weight_array must be one-dimensional.")

    if len(X) != len(y_bool) or len(X) != len(weight_array):
        raise ValueError(
            "X, y_bool, and weight_array must have the same length."
        )

    if laplace < 0:
        raise ValueError("laplace must be non-negative.")

    n_rows, n_columns = X.shape

    y_array = y_bool.to_numpy(
        dtype=np.bool_,
        copy=False,
    )

    weight_array = np.asarray(
        weight_array,
        dtype=np.float64,
    )

    category_counts = {}
    woe = {}

    woe_values = np.zeros(
        (n_rows, n_columns),
        dtype=np.float64,
    )

    for j, column in enumerate(X.columns):
        codes, categories = pd.factorize(
            X[column],
            sort=False,
            use_na_sentinel=True,
        )

        codes = codes.astype(
            np.int64,
            copy=False,
        )

        n_categories = len(categories)

        if n_categories == 0:
            category_counts[column] = {}
            woe[column] = {}
            continue

        counts, category_woe = _aggregate_woe_numba(
            codes,
            y_array,
            weight_array,
            n_categories,
            float(laplace),
        )

        category_keys = (
            categories
            .astype(str)
            .to_numpy()
        )

        category_counts[column] = dict(
            zip(
                category_keys,
                counts.tolist(),
            )
        )

        woe[column] = dict(
            zip(
                category_keys,
                category_woe.tolist(),
            )
        )

        observed = codes >= 0

        woe_values[observed, j] = (
            category_woe[codes[observed]]
        )

    woe_table = pd.DataFrame(
        woe_values,
        index=X.index,
        columns=X.columns,
    )

    return {
        "count": category_counts,
        "woe": woe,
        "woe_table": woe_table,
    }

def apply_woe(
    X,
    woe,
):
    """
    Apply fitted WoE mappings to categorical columns.

    Unknown categories and missing values are assigned WoE=0.

    Args:
      X:
        DataFrame containing categorical variables.
      woe:
        Nested dictionary of WoE mappings.

    Returns:
      WoE-transformed DataFrame with the same index and columns as X.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a DataFrame.")

    if not isinstance(woe, dict):
        raise TypeError("woe must be a dictionary.")

    missing_vars = [
        var for var in X.columns
        if var not in woe
    ]

    if missing_vars:
        raise ValueError(
            f"WoE mappings are missing for variables: {missing_vars}"
        )

    result = np.zeros(
        X.shape,
        dtype=np.float64,
    )

    for j, var in enumerate(X.columns):
        xc = X[var]

        if not isinstance(xc.dtype, pd.CategoricalDtype):
            raise TypeError(
                f"X[{var!r}] must have category dtype."
            )

        codes = xc.cat.codes.to_numpy(
            dtype=np.int64,
            copy=False,
        )

        categories = xc.cat.categories
        mapping = woe[var]

        category_woe = np.fromiter(
            (
                mapping.get(str(category), 0.0)
                for category in categories
            ),
            dtype=np.float64,
            count=len(categories),
        )

        valid = codes >= 0

        result[valid, j] = category_woe[
            codes[valid]
        ]

    return pd.DataFrame(
        result,
        index=X.index,
        columns=X.columns,
    )

def calculate_cross_fitted_woe(
    X,
    y,
    weight=None,
    *,
    n_splits=5,
    shuffle=True,
    random_state=None,
    laplace=LAPLACE,
):
    """
    Calculate cross-fitted Weight of Evidence.

    For each fold:
      1. WoE mappings are estimated using the training folds.
      2. The mappings are applied only to the validation fold.

    WoE mappings are also estimated using the full dataset so that
    new or test data can later be transformed.

    Args:
      X:
        DataFrame containing categorical variables.
        Numerical variables must be discretized beforehand.
      y:
        Binary target. ndarray, Series, or list.
      weight:
        Optional one-dimensional ndarray of sample weights.
      n_splits:
        Number of cross-fitting folds.
      shuffle:
        Whether to shuffle samples before splitting.
      random_state:
        Random seed used when shuffle=True.
      laplace:
        Laplace smoothing constant.

    Returns:
      Dict with the following keys:
        y_bool:
          Boolean Series representing the positive class.
        woe_table:
          Cross-fitted WoE-transformed DataFrame.
        count:
          Category counts estimated using the full dataset.
        woe:
          WoE mappings estimated using the full dataset.
        fold:
          Series containing the validation-fold number of each row.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    y_bool = make_y_bool(
        y,
        index=X.index,
    )

    weight_array = make_sample_weight(
        weight,
        len(X),
    )

    result = _calculate_cross_fitted_woe_main(
        X,
        y_bool,
        weight_array,
        n_splits=n_splits,
        shuffle=shuffle,
        random_state=random_state,
        laplace=laplace,
    )

    return {
        "y_bool": y_bool,
        **result,
    }

def _calculate_cross_fitted_woe_main(
    X,
    y_bool,
    weight_array,
    *,
    n_splits=5,
    shuffle=True,
    random_state=None,
    laplace=LAPLACE,
):
    """
    Calculate cross-fitted WoE using preprocessed target and weights.

    Args:
      X:
        DataFrame containing categorical variables.
      y_bool:
        Boolean Series aligned with X.
      weight_array:
        One-dimensional NumPy array aligned with X.
      n_splits:
        Number of cross-fitting folds.
      shuffle:
        Whether to shuffle before splitting.
      random_state:
        Random seed used when shuffle=True.
      laplace:
        Laplace smoothing constant.

    Returns:
      Dict containing:
        woe_table:
          Cross-fitted WoE table.
        count:
          Category counts fitted on the full dataset.
        woe:
          WoE mappings fitted on the full dataset.
        fold:
          Validation-fold number for each sample.
    """
    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    if not isinstance(y_bool, pd.Series):
        raise TypeError("y_bool must be a pandas Series.")

    if y_bool.dtype != bool:
        raise TypeError("y_bool must be a boolean Series.")

    if not isinstance(weight_array, np.ndarray):
        raise TypeError("weight_array must be a NumPy ndarray.")

    if weight_array.ndim != 1:
        raise ValueError("weight_array must be one-dimensional.")

    if len(X) != len(y_bool) or len(X) != len(weight_array):
        raise ValueError(
            "X, y_bool, and weight_array must have the same length."
        )

    if not isinstance(n_splits, int) or isinstance(n_splits, bool):
        raise TypeError("n_splits must be an integer.")

    if n_splits < 2:
        raise ValueError("n_splits must be at least 2.")

    cv = StratifiedKFold(
        n_splits=n_splits,
        shuffle=shuffle,
        random_state=random_state if shuffle else None,
    )

    cross_fitted_woe_table = pd.DataFrame(
        index=X.index,
        columns=X.columns,
        dtype=float,
    )

    fold_series = pd.Series(
        index=X.index,
        dtype="Int64",
        name="fold",
    )

    y_array = y_bool.to_numpy(
        dtype=np.bool_,
        copy=False,
    )

    for fold, (train_idx, valid_idx) in enumerate(
        cv.split(X, y_array)
    ):
        X_train = X.iloc[train_idx]
        X_valid = X.iloc[valid_idx]

        y_train = y_bool.iloc[train_idx]
        weight_train = weight_array[train_idx]

        fold_result = _calculate_woe_main_fast(
            X_train,
            y_train,
            weight_train,
            laplace,
        )

        valid_woe_table = apply_woe(
            X_valid,
            fold_result["woe"],
        )

        cross_fitted_woe_table.iloc[valid_idx] = (
            valid_woe_table.to_numpy()
        )

        fold_series.iloc[valid_idx] = fold

    # Full-data WoE is retained for transforming future test data.
    full_result = _calculate_woe_main_fast(
        X,
        y_bool,
        weight_array,
        laplace,
    )

    return {
        "count": full_result["count"],
        "woe": full_result["woe"],
        "woe_table": cross_fitted_woe_table,
        "fold": fold_series,
    }

def _logistic_regression(
    raw,
    y_bool,
    weight,
):
    """
    Perform sigmoid calibration.

    This internal function is used by discrete_naive_bayes_main().

    Args:
      raw:
        One-dimensional array of total Weight of Evidence scores.
      y_bool:
        One-dimensional boolean target variable aligned with raw.
      weight:
        One-dimensional array of non-negative sample weights aligned
        with raw.

    Returns:
      Dict containing the following keys:
        raw_score:
          Array of total Weight of Evidence scores.
        probability:
          Array of calibrated probability estimates for the positive
          class (True).
        c0:
          Intercept of the sigmoid calibration.
        c1:
          Coefficient of the sigmoid calibration.
        iter:
          Number of iterations used to estimate c0 and c1.
    """
    assert len(raw) == len(y_bool) == len(weight), (
        "raw, y_bool, and weight must have the same length."
    )

    # Prior probability. prior[0]: probability of False, prior[1]: probability of True.
    prior = np.array([sum(weight[y_bool == val]) for val in [False, True]])
    prior = prior / sum(prior)

    c0 = np.log(prior[1]) - np.log(prior[0])
    c1 = 0
    iter = 0

    mask = ~np.isnan(raw) & (weight > 0)
    xx = raw[mask]
    yy = np.array(y_bool[mask]).astype(bool)
    ww = weight[mask]

    if not np.all(xx == xx[0]):
        for iter in range(LOGI_MAX_ITER):
            grd = np.sum(
                [
                    ((1 / (1 + np.exp(-(c0 + c1 * x)))) - y) * x * w
                    for x, y, w in zip(xx, yy, ww)
                ],
                axis=0
            )

            hesse22 = np.sum(
                [
                    (
                        1
                        / (1 + np.exp(-(c0 + c1 * x)))
                        * (1 - (1 / (1 + np.exp(-(c0 + c1 * x)))))
                        * x**2
                        * w
                    )
                    for x, y, w in zip(xx, yy, ww)
                ],
                axis=0
            )

            delta_c1 = -grd / hesse22

            if hesse22 < 1e-8 or abs(delta_c1) < 1e-8:
                iter -= 1
                break

            c1 += delta_c1

    p = _calc_probability(c0, c1, raw)

    res = {
        'raw_score': raw,
        'probability': p,
        'c0': c0,
        'c1': c1,
        'iter': iter,
    }

    return res

def _calc_probability(
    c0,
    c1,
    raw,
):
    """
    Convert raw scores into probabilities using sigmoid calibration.

    This internal function is used by discrete_naive_bayes_main()
    and _logistic_regression().

    Args:
      c0:
        Intercept of the sigmoid calibration.
      c1:
        Coefficient of the sigmoid calibration.
      raw:
        Raw score or array of raw scores.

    Returns:
      Probability or array of probabilities.
    """
    if np.isnan(c0):
        c0 = 0
    if np.isnan(c1):
        c1 = 0

    p = 1 / (1 + np.exp(-(c0 + c1 * raw)))

    return p

def get_accuracy_score(
    model,
    X,
    y,
):
    """
    Calculate the accuracy score.

    Args:
      model:
        Trained discrete naive Bayes model generated by
        discrete_naive_bayes().
      X:
        DataFrame containing categorical variables. Numerical variables
        must be discretized into categorical variables beforehand.
      y:
        One-dimensional array-like target variable with the same number
        of observations as X.

    Returns:
      Accuracy score.
    """
    if not isinstance(model, dict):
        raise TypeError("model must be a dictionary.")

    if not is_discrete_naive_bayes(model):
        raise ValueError(
            "model must be a discrete naive Bayes model generated by "
            "discrete_naive_bayes()."
        )

    if not isinstance(X, pd.DataFrame):
        raise TypeError("X must be a pandas DataFrame.")

    y = np.asarray(y)

    if y.ndim != 1:
        raise ValueError("y must be one-dimensional.")

    if len(y) != len(X):
        raise ValueError("y must have the same length as X.")

    y_true = make_y_bool(y).to_numpy(dtype=np.bool_, copy=False)

    pred = predict_dnb(model, X)
    y_pred = pred['probability'] >= 0.5
    acc = accuracy_score(y_true, y_pred)

    return acc

def get_iv(
    model,
    variables=None,
):
    """
    Return the information value (IV) of variables.

    Args:
      model:
        Discrete naive Bayes model generated by discrete_naive_bayes().
      variables:
        List of variable names. If None, all variables are used.

    Returns:
      Dict containing the information value (IV) for each variable.
    """
    if not isinstance(model, dict):
        raise TypeError("model must be a dictionary.")

    if not is_discrete_naive_bayes(model):
        raise ValueError(
            "model must be a discrete naive Bayes model generated by "
            "discrete_naive_bayes()."
        )

    if variables is not None and not isinstance(variables, list):
        raise TypeError("variables must be a list or None.")

    train = model['train']
    y_bool = train['y_bool']

    if variables is None:
        variables = train['woe'].keys()

    iv = {}
    for var in variables:
        if var in train['woe'].keys():
            woe_vec = train['woe_table'][var]
            iv[var] = float(np.mean(woe_vec[y_bool]) - np.mean(woe_vec[~y_bool]))
        else:
            iv[var] = None

    return iv

def plot_iv(
    iv,
):
    """
    Plot information value (IV) for variables.

    Variables are ordered by IV in descending order.

    Args:
      iv:
        Dictionary whose keys are variable names and values are
        information values (IV).
    """
    if not isinstance(iv, dict):
        raise TypeError("iv must be a dictionary.")

    plot_data = pd.DataFrame({
        "variable": list(iv.keys()),
        "iv": list(iv.values()),
    }).sort_values(
        "iv",
        ascending=False,
    )

    fig, ax = plt.subplots(
        figsize=(7, max(3, 0.3 * len(plot_data)))
    )

    sns.barplot(
        data=plot_data,
        x="iv",
        y="variable",
        order=plot_data["variable"],
        errorbar=None,
        ax=ax,
    )

    ax.set(
        xlabel="Information Value (IV)",
        ylabel=None,
    )

    sns.despine(
        ax=ax,
        left=True,
        bottom=True,
    )

    fig.tight_layout()
    plt.show()

def plot_woe(
    model,
    variables=None,
):
    """
    Display Weight of Evidence (WoE) plots for variables.

    Args:
      model:
        Discrete naive Bayes model generated by discrete_naive_bayes().
      variables:
        List of variable names. If None, all variables are plotted.

    Returns:
      None.
    """
    if not isinstance(model, dict):
        raise TypeError("model must be a dictionary.")

    if not is_discrete_naive_bayes(model):
        raise ValueError(
            "model must be a discrete naive Bayes model generated by "
            "discrete_naive_bayes()."
        )

    if variables is not None and not isinstance(variables, list):
        raise TypeError("variables must be a list or None.")


    def plot_woe_main(
        model,
        var,
    ):
        disc = model["disc"]
        train = model["train"]
        y_bool = train["y_bool"]
        key_cnt = train["count"][var]
        woe = train["woe"][var]
        woe_vec = train["woe_table"][var]

        iv = float(
            np.mean(woe_vec[y_bool])
            - np.mean(woe_vec[~y_bool])
        )

        plot_data = pd.DataFrame({
            "category": [
                f"{cat} (N={key_cnt[cat]})"
                for cat in woe.keys()
            ],
            "woe": list(woe.values()),
        })

        fig, ax = plt.subplots(
            figsize=(7, max(3, 0.3 * len(plot_data)))
        )

        sns.barplot(
            data=plot_data,
            x="woe",
            y="category",
            orient="h",
            errorbar=None,
            ax=ax,
        )

        ax.axvline(
            0,
            linestyle="--",
            linewidth=1,
        )

        ax.set(
            title=f"{var}  (IV = {iv:.3f})",
            xlabel="Weight of Evidence (WoE)",
            ylabel=None,
        )

        sns.despine(
            ax=ax,
            left=True,
            bottom=True,
        )

        fig.tight_layout()
        plt.show()

        return iv


    if variables is None:
        all_variables = model['train']['woe'].keys()
        iv_list = [plot_woe_main(model, var) for var in all_variables]
        ivs = dict(zip(all_variables, iv_list))

    else:
        iv_list = [plot_woe_main(model, var) for var in variables]
        ivs = dict(zip(variables, iv_list))

    return ivs

"""
scikit-learn compliant class that provides methods for discrete naive Bayes.
"""
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.utils.validation import check_is_fitted
from sklearn.exceptions import NotFittedError

class DiscreteNaiveBayes(BaseEstimator, ClassifierMixin):

    def __init__(
        self,
        discretizer='bic',
        cross_fitting=False,
        n_splits=5,
        shuffle=True,
        random_state=None,
    ):
        self.discretizer = discretizer
        self.cross_fitting = cross_fitting
        self.n_splits = n_splits
        self.shuffle = shuffle
        self.random_state = random_state

    def __sklearn_tags__(
        self,
    ):
        tags = super().__sklearn_tags__()
        tags.estimator_type = "classifier"
        tags.input_tags.allow_nan = True
        return tags

    def fit(
        self,
        X,
        y,
        weight=None,
    ):
        ycat = pd.Categorical(y)
        self.classes_ = np.array(ycat.categories)
        self.coef_ = discrete_naive_bayes(
            X,
            y,
            weight=weight,
            discretizer=self.discretizer,
            cross_fitting=self.cross_fitting,
            n_splits=self.n_splits,
            shuffle=self.shuffle,
            random_state=self.random_state,
        )
        return self

    def predict(
        self,
        X,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        pred = predict_dnb(self.coef_, X)
        return (pred['probability'] >= 0.5)

    def predict_proba(
        self,
        X,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        pred = predict_dnb(self.coef_, X)
        p = pred['probability']
        return np.stack([1 - p, p], 1)

    def score(
        self,
        X,
        y,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        return get_accuracy_score(
            self.coef_,
            X,
            y,
        )

    def get_iv(
        self,
        variables=None,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        return get_iv(
            self.coef_,
            variables,
        )

    def plot_iv(
        self,
        variables=None,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        iv = get_iv(
            self.coef_,
            variables=variables,
        )
        return plot_iv(iv)


    def plot_woe(
        self,
        variables=None,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        return plot_woe(
            self.coef_,
            variables
        )

    def get_model(
        self,
    ):
        try:
            check_is_fitted(self, attributes=['coef_', 'classes_'])
        except NotFittedError as exc:
            print(f"The model is not fitted yet.")

        return self.coef_

